SELECT BOARD.WRITER_ID AS USER_ID, USER.NICKNAME, SUM(BOARD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS BOARD 
    JOIN USED_GOODS_USER AS USER ON BOARD.WRITER_ID =USER.USER_ID
WHERE BOARD.STATUS="DONE"
GROUP BY BOARD.WRITER_ID
HAVING SUM(BOARD.PRICE)>=700000
ORDER BY TOTAL_SALES


-- 코드를 입력하세요
# SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD AS A
# JOIN USED_GOODS_USER AS B
# ON A.WRITER_ID = B.USER_ID
# WHERE A.STATUS = 'DONE'
# GROUP BY B.USER_ID >= 700000
# ORDER BY TOTAL_SALES;
