-- 코드를 입력하세요
SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER >= 3000 AND B.INGREDIENT_TYPE ='fruit_based'

# SELECT FLAVOR
# FROM FIRST_HALF
# WHERE TOTAL_ORDER > 3000

# SELECT FLAVOR
# FROM ICECREAM_INFO
# WHERE INGREDIENT_TYPE = 'fruit_based'